### ISSUE TITLE
А зачем этот метод run?

### ISSUE THREAD

**Issue by AlexKenbo** [PlugFox/router#7]
https://github.com/PlugFox/router/blob/3bc33a6a38128144b2c46f47fa19c78e60de19b7/lib/src/app.dart#L8

**Comment by PlugFox** [comment]
А зачем метод `runApp`?

https://github.com/flutter/flutter/blob/18116933e7/packages/flutter/lib/src/widgets/binding.dart#L1034-L1038

Ответ: за него инкапсулирована часть логики о которой не надо знать вызывающему
