### ISSUE TITLE
[BUG] В примере пропал дебаггер

### ISSUE THREAD

**Issue by AlexKenbo** [PlugFox/router#9]
https://example.plugfox.dev/router/#home/color-red/accent-red-200

Нету внизу дебагера как в видео.

![image](https://user-images.githubusercontent.com/14903011/145163906-c115f89c-f326-4a09-9bb9-aef3ee1c6c49.png)

**Comment by PlugFox** [comment]
https://github.com/PlugFox/router/blob/master/lib/src/common/router/router_delegate.dart#L90

Для его отображения должно выполняться ряд условий:
https://github.com/PlugFox/router/blob/master/lib/src/common/router/router_delegate.dart#L59

**Comment by AlexKenbo** [comment]
Если <796 пикселей высота, то не выводит..

На макбуках 13 дюймов не работает:)

80%
![image](https://user-images.githubusercontent.com/14903011/145227634-51ca331f-17e6-4028-9f7b-780a515e4f84.png)
